/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 94710
 */
public class lab1 extends javax.swing.JFrame {

    /**
     * Creates new form lab1
     */
    public lab1() {
        initComponents();
    }
    PreparedStatement pstmt;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void fetchDataAndDisplayInTable()
  {
   try{
   
      Connection con = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
      Statement statement = con.createStatement();
      String query = "SELECT Quantity, Tools FROM lab"; 
      ResultSet resultSet = statement.executeQuery(query);
       
       DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Tools");
            tableModel.addColumn("Quantity");


      
      while (resultSet.next())
       {
                String tools = resultSet.getString("Tools");
                int quantity = resultSet.getInt("Quantity");

                 tableModel.addRow(new Object[]{tools, quantity});
                
            }
               jTablel2.setModel(tableModel);

            // Close resources
            resultSet.close();
            statement.close();
            con.close();
      
      
   }catch(Exception ex){
            System.out.println(ex);
        }
   
   
  
  }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndelete = new javax.swing.JButton();
        btnInsret = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablel2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTools1 = new javax.swing.JTextField();
        txtQu1 = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        btnInsret.setText("INSERT");
        btnInsret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsretActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsret, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jTablel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tools", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTablel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 436, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("LAB Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 210, -1));

        jLabel2.setText("Tools");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 89, 27));

        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 69, -1));
        getContentPane().add(txtTools1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, -1));
        getContentPane().add(txtQu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 220, -1));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        btnprint.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\94710\\Desktop\\light-color-background-1eq9mtpjqjz9ddep.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsretActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
            pstmt= con.prepareStatement("insert into lab values(?,?)");
            String a= txtTools1.getText();
            String b= txtQu1.getText();
            pstmt.setString(1,a);
            pstmt.setString(2,b);
            pstmt.executeUpdate();
        }catch(Exception ex){
            System.out.println(ex);
        }
        fetchDataAndDisplayInTable();
    }//GEN-LAST:event_btnInsretActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
        PreparedStatement pstmt= con.prepareStatement("update lab set Quantity=? where Tools=?");
        String a= txtTools1.getText();
        String b= txtQu1.getText();
               pstmt.setString(1,b);
               pstmt.setString(2,a);
               //psu.setString(1,"abc");
               //psu.setString(2,"dff");
               pstmt.executeUpdate();
               JOptionPane.showMessageDialog(this,"tools and quantity are updated."); 
        }catch(Exception ex){
         System.out.print(ex);
        }
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
          try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
        pstmt=con.prepareStatement("delete from lab where Tools=?");
        String a= txtTools1.getText();
            pstmt.setString(1,a);
            //psd.setString(1,"df");
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"tools and quantity are deleted."); 
         }catch(Exception ex){
         System.out.print(ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
           selectFrom sf = new selectFrom();
           sf.show();
           this.hide();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        this.hide();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed

        fetchDataAndDisplayInTable();
        
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try{
            jTablel2.print();
        }
        catch(Exception e){
            e.printStackTrace();
        }
                      
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsret;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablel2;
    private javax.swing.JTextField txtQu1;
    private javax.swing.JTextField txtTools1;
    // End of variables declaration//GEN-END:variables

 private void table_update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
