/*y7u
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;


import java.awt.Button;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 94710
 */
public class WARD extends javax.swing.JFrame {

    /**
     * Creates new form WORD
     */
    public WARD() {
        initComponents();
    }
    PreparedStatement pstmt;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtTools = new javax.swing.JTextField();
        btnInsret = new javax.swing.JButton();
        txtQu = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("WARD Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 40));

        jLabel2.setText("Tools");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 89, 27));

        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 69, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tools", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 436, -1));
        getContentPane().add(txtTools, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 240, -1));

        btnInsret.setText("INSERT");
        btnInsret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsretActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsret, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        getContentPane().add(txtQu, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 220, 240, -1));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        btnprint.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\94710\\Desktop\\light-color-background-1eq9mtpjqjz9ddep.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       
 try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
        PreparedStatement pstmt= con.prepareStatement("update ward set Quantity=? where Tools=?");
        String a= txtTools.getText();
        String b= txtQu.getText();
               pstmt.setString(1,b);
               pstmt.setString(2,a);
               //psu.setString(1,"abc");
               //psu.setString(2,"dff");
               pstmt.executeUpdate();
               JOptionPane.showMessageDialog(this,"tools and quantity are updated."); 
        }catch(Exception ex){
         System.out.print(ex);
        }
    
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnInsretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsretActionPerformed
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
        pstmt= con.prepareStatement("insert into ward values(?,?)");
        String a= txtTools.getText();
        String b= txtQu.getText();
        pstmt.setString(1,a);
        pstmt.setString(2,b);
        pstmt.executeUpdate();
        }catch(Exception ex){
            System.out.println(ex);
        }
        fetchDataAndDisplayInTable();
    }//GEN-LAST:event_btnInsretActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
        pstmt=con.prepareStatement("delete from ward where Tools=?");
        String a= txtTools.getText();
            pstmt.setString(1,a);
            //psd.setString(1,"df");
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"tools and quantity are deleted."); 
         }catch(Exception ex){
         System.out.print(ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectFrom sf = new selectFrom();
        sf.show();
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        this.hide();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
     fetchDataAndDisplayInTable();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try{
            jTable1.print();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnprintActionPerformed
  private void fetchDataAndDisplayInTable()
  {
   try{
   
      Connection con = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/tools","root","");
      Statement statement = con.createStatement();
      String query = "SELECT Quantity, Tools FROM ward"; 
      ResultSet resultSet = statement.executeQuery(query);
           
       DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Tools");
            tableModel.addColumn("Quantity");


      
      while (resultSet.next())
       {
                String tools = resultSet.getString("Tools");
                int quantity = resultSet.getInt("Quantity");

                 tableModel.addRow(new Object[]{tools, quantity});
                
            }
               jTable1.setModel(tableModel);

            // Close resources
            resultSet.close();
            statement.close();
            con.close();
      
      
   }catch(Exception ex){
            System.out.println(ex);
        }
   
   
  
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsret;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtQu;
    private javax.swing.JTextField txtTools;
    // End of variables declaration//GEN-END:variables

    private void table_update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
